

###Get all products
GET http://localhost:3001/api/products

###Get product by id
GET http://localhost:3001/api/products/1

###Get all orders
GET http://localhost:3001/api/orders

###Get order by id
GET http://localhost:3001/api/orders/1

###Get all inventory
GET http://localhost:3001/api/inventory

###Get inventory by id
GET http://localhost:3001/api/inventory/1

### Post purchase
POST http://localhost:3001/api/purchase
Content-Type: application/json

{
  "productId": "123",
  "quantity": 1,
  "userId": "user123"
}